baseURL: "https://examplesite.com/"
title: "kngm-blog"
paginate: 5
theme: PaperMod
defaultContentLanguage: ja
hasCJKLanguage: true

enableInlineShortcodes: true
enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false
enableEmoji: true

minify:
  disableXML: true
  minifyOutput: true

taxonomies:
  category: categories
  tag: tags

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: "kngm-blog"
  description: "ExampleSite description"
  keywords: [Blog, Portfolio, PaperMod]
  images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: false
  ShowShareButtons: false
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  ShowWordCount: false
  ShowRssButtonInSectionTermList: false
  UseHugoToc: true
  disableSpecial1stPost: true
  disableScrollToTop: true
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: true
  tocopen: true

  label:
    text: "kngm-blog"
    icon: /apple-touch-icon.png
    iconHeight: 35

  profileMode:
    enabled: false

  socialIcons:
    - name: github
      url: "https://github.com/"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: true # hide on single page

menu:
  main:
    - identifier: about
      name: About
      url: about/
      weight: 10
    - identifier: posts
      name: Posts
      url: posts/
      weight: 10
    - identifier: tags
      name: Tags
      url: /tags/
      weight: 30
